#!/usr/bin/expect -f

set timeout 5

set token [lindex $argv 0]
set action [lindex $argv 1]

if { $argc >= 3 } {
    set extra_args [lrange $argv 2 end]
    spawn git $action {*}$extra_args
} else {
    spawn git $action
}

expect "Username for 'https://github.com':"
send -- "madophs\n"

expect "Password for 'https://madophs@github.com':"
send -- "$token\n"

expect eof

send_user "Developed by Jehú Jair Ruiz Villegas\n"
